//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Интернет_магазин_Черешня
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Coordinates> Coordinates { get; set; }
        public virtual DbSet<Earth> Earth { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Potrebnost> Potrebnost { get; set; }
        public virtual DbSet<Potrebnost_apartment> Potrebnost_apartment { get; set; }
        public virtual DbSet<Potrebnost_earth> Potrebnost_earth { get; set; }
        public virtual DbSet<Potrebnost_house> Potrebnost_house { get; set; }
        public virtual DbSet<Predlozheniye> Predlozheniye { get; set; }
        public virtual DbSet<Realtor> Realtor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
