//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Интернет_магазин_Черешня
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ID { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Address_House { get; set; }
        public Nullable<int> Address_Number { get; set; }
        public string Tip_object { get; set; }
        public Nullable<int> FK_Apartment { get; set; }
        public Nullable<int> FK_Earth { get; set; }
        public Nullable<int> FK_House { get; set; }
        public Nullable<int> FK_Predlozheniye { get; set; }
        public Nullable<int> FK_Coordinates { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Coordinates Coordinates { get; set; }
        public virtual Earth Earth { get; set; }
        public virtual House House { get; set; }
        public virtual Predlozheniye Predlozheniye { get; set; }
    }
}
