//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Интернет_магазин_Черешня
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potrebnost_house
    {
        public int ID { get; set; }
        public Nullable<int> Min_ploshchad { get; set; }
        public Nullable<int> Max_ploshchad { get; set; }
        public Nullable<int> Min_numb_rooms { get; set; }
        public Nullable<int> Max_numb_rooms { get; set; }
        public Nullable<int> Min_floor { get; set; }
        public Nullable<int> Max_floor { get; set; }
        public int FK_Potrebnost { get; set; }
    
        public virtual Potrebnost Potrebnost { get; set; }
    }
}
